### ISSUE TITLE
Error: Cannot find module 'babel-runtime/helpers'

### ISSUE THREAD

**Issue by balupton** [daliwali/docchi#3]
Trying to run Docchi on https://github.com/bevry/taskgroup `es6` branch

```
$ npm i docchi
$ ./node_modules/.bin/docchi < es6/lib/taskgroup.js
module.js:318
    throw err;
          ^
Error: Cannot find module 'babel-runtime/helpers'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/Users/balupton/Projects/taskgroup/node_modules/docchi/dist/lib/cli.js:3:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
```

**Comment by daliwali** [comment]
Thanks for notifying, it may have to do with breaking changes in dependencies. Trying to fix docchi to work with 1.0 major release of Acorn right now.

**Comment by daliwali** [comment]
I bumped the package to `0.5.0` just now, let me know if you are still having this problem.
